#@url = http://localhost:9001
@url = http://192.168.1.14:9001

### ADMIN
POST http://{{url}}/realms/ShotYourPet/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
client_id = shotyourpet &
username = user &
password = user &
scope = offline_access

> {%
    client.global.set("auth_token_admin", "Bearer " + response.body.access_token);
%}