#@url = http://localhost:8084
@url = http://localhost/api

###
GET {{url}}/utilisateurs/profile
Authorization: {{auth_token_admin}}

###
GET {{url}}/utilisateurs/utilisateurs
Authorization: {{auth_token_admin}}

###
PUT {{url}}/utilisateurs/avatar
Authorization: {{auth_token_admin}}
Content-Type: application/json

{
  "idImage": ""
}