services:

  nginx:
    image: nginx:alpine
    container_name: gateway_container_syp
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - utilisateur
      - images
      - frontend

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    restart: unless-stopped
    container_name: keycloak_container_syp
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_EVENTS_LISTENERS: "shot_your_pet_event_listener,email"
      JAVA_OPTS_APPEND: "-Drabbitmq.host=${RABBITMQ_HOST} -Drabbitmq.port=${RABBITMQ_PORT} -Drabbitmq.username=${RABBITMQ_USERNAME} -Drabbitmq.password=${RABBITMQ_PASSWORD}"
      # KC_DB: mariadb
      # KC_DB_URL: jdbc:mariadb://keycloak-bd:3306/keycloak
      # KC_DB_USERNAME: admin
      # KC_DB_PASSWORD: admin
    ports:
      - "9001:8080"
    volumes:
      - "./SPI_Keycloak.jar:/opt/keycloak/providers/syp-event-listener.jar"
      - "./realm-syp.json:/opt/keycloak/data/import/realm-export.json"
    command: start-dev --import-realm
    depends_on:
      - rabbitmq

  utilisateur:
    image: ghcr.io/shot-your-pet/utilisateur-groupe9/${UTILISATEUR_IMAGE}
    container_name: utilisateur_container_syp
    restart: unless-stopped
    ports:
      - "8084:8080"
    environment:
      DB_DB: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mariadb
      DB_PORT: 3306
      AUTH_PROVIDER_URL: ${AUTH_PROVIDER_URL}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_started
      mariadb:
        condition: service_healthy
  images:
    image: ghcr.io/shot-your-pet/images-groupe9/${IMAGES_IMAGE}
    container_name: images_container_syp
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      MONGO_BD: ${MONGO_BD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      IMAGE_PATH: ${IMAGE_PATH}
      REALM_KEYCLOAK_URL: ${REALM_KEYCLOAK_URL}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      ALLOWED_CORS: ${ALLOWED_CORS}
    depends_on:
      - rabbitmq
      - mongodb_image
      - keycloak

  frontend:
    image: ghcr.io/shot-your-pet/frontend-groupe9/${FRONTEND_IMAGE}
    container_name: frontend_container_syp
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      API_URL: ${API_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq_container_syp
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret_cookie"

  mongodb_image:
    image: mongo:8.0.5
    container_name: mongodb-image_container_syp
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"

  mariadb:
    image: mariadb:11.0.2
    container_name: utilisateur_db_container_syp
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: mariadb-admin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 10s
      start_period: 5s
      retries: 10
  publications:
    image: ghcr.io/shot-your-pet/publications:latest
    pull_policy: always
    container_name: publications_container_syp
    restart: unless-stopped
    ports:
      - "8085:8080"
    networks:
      - publications
    depends_on:
      rabbitmq:
        condition: service_started
      mariadb:
        condition: service_healthy
    environment:
      MONGODB_HOST: publications_image
      MONGODB_USERNAME: ${MONGO_USERNAME}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      REALM_KEYCLOAK_URL: ${KEYCLOAK_REALM}
      RABBIT_MQ_ADDRESS: amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/
  publications_image:
    image: mongo:8.0.5
    container_name: mongodb-publications_container_syp
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PUBLICATIONS_MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${PUBLICATIONS_MONGODB_USERNAME}
    networks:
      - publications
networks:
  publications:
