global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape des métriques de Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape des métriques de Keycloak
  - job_name: 'keycloak'
    metrics_path: /metrics
    static_configs:
      - targets: ['keycloak_container_syp:8080']

  # Scrape des métriques du service "utilisateurs"
  - job_name: 'utilisateurs'
    metrics_path: /metrics
    static_configs:
      - targets: ['utilisateurs_container_syp:8080']

  # Scrape des métriques du service "images"
  - job_name: 'images'
    metrics_path: /metrics
    static_configs:
      - targets: ['images_container_syp:8080']

  # Scrape des métriques du service "publications"
  - job_name: 'publications'
    metrics_path: /metrics
    static_configs:
      - targets: ['publications_container_syp:8080']

  # Scrape des métriques du service "challenges"
  - job_name: 'challenges'
    metrics_path: /metrics
    static_configs:
      - targets: ['challenges_container_syp:8080']

  # Scrape des métriques du service "timeline"
  - job_name: 'timeline'
    metrics_path: /metrics
    static_configs:
      - targets: ['timeline_container_syp:8080']

  # Scrape des métriques du service "notifications"
  - job_name: 'notifications'
    metrics_path: /metrics
    static_configs:
      - targets: ['notifications_container_syp:8080']
